global:
  namespace: helm
service:
  fastapi-app-deploy:
    port: 80
    containerPort: 5000
    type: ClusterIP
    targetPort: 5000
  fastapi:
    targetPort: 5000
    port: 80  # Port pour FastAPI
    type: ClusterIP  # Type de service pour FastAPI
  postgres:
    port: 5432  # Port pour PostgreSQL
    type: ClusterIP  # Type de service pour PostgreSQL
  pgadm:
    port: 80  # Port pour PgAdmin
    type: NodePort  # Type de service pour PgAdmin
    nodePort: 30080  # NodePort pour PgAdmin, si nécessaire
postgres:
  replicaCount: 1
  image:
    repository: postgres  # Remplacer par le bon dépôt d'image
    tag: "12.0-alpine"  # Remplacer par le tag d'image souhaité
  service:
    port: 5432
  env:
    user: admin
    dbname: storedb
  secret:
    encodedPassword: "cGFzc3dvcmQ="
  storage:
    className: local-path
    size: 3Gi
pgadmin:
  image:
    repository: dpage/pgadmin4  # Remplacer par le dépôt d'image si nécessaire
    tag: "latest"  # Remplacer par le tag d'image souhaité
  service:
    port: 80
    nodePort: 30080
  env:
    email: "admin@admin.com"
    password: "root"  # Ne pas mettre le mot de passe directement dans values.yaml pour des raisons de sécurité
exam1DstPv:
  storage: 10Gi
  accessMode: ReadWriteOnce
  hostPath: "/mnt/data"
  storageClassName: slow
exam1DstPvc:
  accessMode: ReadWriteOnce
  storageClassName: local-path
  storage: 3Gi
backupLogPvc:
  accessMode: ReadWriteOnce
  storageClassName: slow
  storage: 1Gi
fastapi:
  service:
    port: 80  # Assurez-vous que cela correspond au port du service FastAPI
    containerPort: 5000
    targetPort: 5000
    type: ClusterIP
  ingress:
    host: mystreamingapp.crs-datascientest.cloudns.biz  # Votre nom de domaine
  replicaCount: 3  # Replica count specific to FastAPI, if different from global
  image:
    repository: pablohassan/fast_api_exam_app  # Replace with your FastAPI image repository
    tag: "helmv1"  # Replace with the desired FastAPI image tag
  hpa:
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
clusterIssuer:
  name: letsencrypt-prod
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sesmanovic@gmail.com
    privateKeySecretRef: letsencrypt-prod
    solvers:
      http01:
        ingress:
          class: traefik
