global:
  namespace: helm

service:
  postgres:
    port: 5432  # Port pour PostgreSQL
    type: ClusterIP  # Type de service pour PostgreSQL
  fastapiAppDeploy:
    port: 5000
    containerPort: 5000
    type: ClusterIP 
  pgadm:
    port: 80  # Port pour PgAdmin
    type: NodePort  # Type de service pour PgAdmin
    nodePort: 30080  # NodePort pour PgAdmin, si nécessaire

postgres:
  replicaCount: 1
  image:
    repository: postgres  # Remplacer par le bon dépôt d'image
    tag: "12.0-alpine"  # Remplacer par le tag d'image souhaité
  service:
    port: 5432
  env:
    user: admin
    dbname: storedb
  secret:
  #encodedPassword: ""
  storage:
    className: local-path
    size: 3Gi

pgadmin:
  image:
    repository: dpage/pgadmin4  # Remplacer par le dépôt d'image si nécessaire
    tag: "latest"  # Remplacer par le tag d'image souhaité
  service:
    port: 80
    nodePort: 30080
  env:
    email: "admin@admin.com" 
    #encodedPassword:""
exam1DstPv:
  storage: 10Gi
  accessMode: ReadWriteOnce
  hostPath: "/mnt/data"
  storageClassName: slow

fastapi:
  replicaCount: 3
  ingress:
    host: mystreamingapp.crs-datascientest.cloudns.biz  # Votre nom de domaine
  image:
    repository: pablohassan/fast_api_exam_app
    tag: helmv1
  containerPort: 5000
  port: 80
  hpa:
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
  resources:
    requests:
      cpu: "100m"

clusterIssuer:
  name: letsencrypt-prod
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sesmanovic@gmail.com
    privateKeySecretRef: letsencrypt-prod
    solvers:
      http01:
        ingress:
          class: traefik
