apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
  volumeName: exam1-dst-pv
