apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exam1-dst-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 3Gi
  volumeName: exam1-dst-pv
