apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  postgres-password: {{ .Values.postgres.secret.encodedPassword }}

